### PR TITLE
Feature/dsp 393 ui bootstrap 2

### PR DESCRIPTION
**Pull request by smlombardi**
Second time around.  Updated ui-bootstrap library and related code.  Updated popups to use new event.

### CODE REVIEW

**Comment by danielcollettepb** [comment]
On Tables, these accordions and tabs are not working, please check globally.

image

**Comment by danielcollettepb** [comment]
All references to ui-bootstrap need to be updated to the latest version:

image

**Comment by danielcollettepb** [comment]
This text should not be lorem ipsum:

image

**Comment by lombardi-gux** [comment]
these items are unrelated to the PR

it's apparently like this on the live site

On Apr 7, 2016, at 3:00 PM, danielcollettepb <notifications@github.com<mailto:notifications@github.com>> wrote:


This text should not be lorem ipsum:

[image]<https://cloud.githubusercontent.com/assets/6116867/14363293/7cd75c08-fcd1-11e5-8b3b-b5259e00c94a.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/PBGUX/designsystem/pull/97#issuecomment-207050474>


________________________________

**Comment by lombardi-gux** [comment]
where is this?  because i updated it on the modals/popovers page
On Apr 7, 2016, at 2:59 PM, danielcollettepb <notifications@github.com<mailto:notifications@github.com>> wrote:


All references to ui-bootstrap need to be updated to the latest version:

[image]<https://cloud.githubusercontent.com/assets/6116867/14363264/5827dafe-fcd1-11e5-8be0-749ad093f91f.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/PBGUX/designsystem/pull/97#issuecomment-207050190>


________________________________

**Comment by smlombardi** [comment]
Above has been fixed.  The caret in the above was never expanding.  You added it only for "show".  I removed it to avoid confusion.  Expandable rows are demoed elsewhere on the page, and work fine.

**Comment by danielcollettepb** [comment]
created bug in JIRA for Faceted Search usage copy, other changes look good.

**Pull request merged**
